services:
  - type: web
    name: collanote
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && npm run setup
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
